-- INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas)
Use FNAC;
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (1,'Harper Lee','Classics','Porto Editora',226);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (2,'Jane Austen','Classics','Antígona',391);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (3,'Anne Frank','Classics','Harper Collins',246);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (4,'George Orwell','Dystopian','Penguin Books',376);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (5,'J.K. Rowling','Fantasy','Cavalo de Ferro',390);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (6,'J.R.R. Tolkien','Fantasy','Porto Editora',318);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (7,'F. Scott Fitzgerald','Classics','Usborne Publishing',318);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (8,'E.B. White','Classics','Editorial Presença',280);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (9,'Louisa May Alcott','Classics','Harper Collins',412);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (10,'J.R.R. Tolkien','Fantasy','Penguin Books',393);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (11,'Ray Bradbury','Classics','Harper Collins',255);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (12,'Charlotte Bronte','Classics','Sextante Editora',411);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (13,'Margaret Mitchell','Classics','Usborne Publishing',295);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (14,'George Orwell','Dystopian','Editorial Presença',266);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (15,'J.D. Salinger','Classics','Porto Editora',237);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (16,'Mark Twain','Classics','Quetzal Editores',397);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (17,'Kathryn Stockett','Classics','Porto Editora',421);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (18,'John Steinbeck','Classics','Faber and Faber',223);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (19,'C.S. Lewis','Classics','Usborne Publishing',222);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (20,'Suzanne Collins','Dystopian','Harper Collins',367);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (21,'Markus Zusak','Classics','Penguin Books',236);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (22,'William Golding','Classics','Usborne Publishing',246);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (23,'Khaled Hosseini','Classics','Harper Collins',304);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (24,'Elie Wiesel','Classics','Editorial Presença',367);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (25,'William Shakespeare','Classics','Penguin Books',334);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (26,'Charles Dickens','Classics','Editorial Presença',226);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (27,'Madeline L’Engle','Classics','Porto Editora',406);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (28,'Douglas Adams','Sci-Fi','Sextante Editora',274);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (29,'Charles Dickens','Classics','Usborne Publishing',384);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (30,'John Steinbeck','Classics','Editorial Presença',349);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (31,'Frances Hodgson Burnett','Classics','Porto Editora',280);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (32,'William Shakespeare','Classics','Faber and Faber',318);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (33,'Margaret Atwood','Classics','Usborne Publishing',223);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (34,'Aldous Huxley','Dystopian','Harper Collins',311);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (35,'Antoine Saint-Exupery','Classics','Penguin Books',377);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (36,'Shel Silverstein','Classics','Porto Editora',258);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (37,'Emily Bronte','Classics','Antígona',294);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (38,'Lois Lowry','Classics','Harper Collins',316);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (39,'L.M. Montgomery','Classics','Penguin Books',412);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (40,'William Shakespeare','Classics','Cavalo de Ferro',410);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (41,'Mark Twain','Classics','Porto Editora',365);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (42,'J.K. Rowling','Fantasy','Usborne Publishing',291);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (43,'Mary Shelley','Classics','Editorial Presença',331);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (44,'Thomas Nelson','Classics','Harper Collins',336);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (45,'Stieg Larsson','Classics','Penguin Books',224);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (46,'Alexandre Dumas pere','Classics','Harper Collins',360);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (47,'John Green','Classics','Sextante Editora',393);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (48,'Alice Walker','Classics','Usborne Publishing',413);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (49,'John Steinbeck','Classics','Editorial Presença',354);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (50,'Betty Smith','Classics','Porto Editora',416);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (51,'Joseph Heller','Classics','Quetzal Editores',314);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (52,'Truman Capote','Classics','Porto Editora',284);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (53,'Stephen King','Horror','Antígona',226);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (54,'Lewis Carroll','Classics','Harper Collins',431);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (55,'Richard Adams','Classics','Penguin Books',418);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (56,'Leo Tolstoy','Classics','Cavalo de Ferro',365);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (57,'Orson Scott Card','Sci-Fi','Porto Editora',380);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (58,'Charles Dickens','Classics','Usborne Publishing',304);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (59,'Daphne du Maurier','Classics','Editorial Presença',427);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (60,'Arthur Golden','Classics','Harper Collins',309);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (61,'Arthur Conan Doyle','Classics','Penguin Books',308);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (62,'J.K. Rowling','Fantasy','Harper Collins',374);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (63,'Ernest Hemingway','Classics','Sextante Editora',402);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (64,'George R.R. Martin','Fantasy','Usborne Publishing',280);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (65,'William Goldman','Classics','Editorial Presença',338);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (66,'Roald Dahl','Classics','Porto Editora',407);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (67,'Yann Martel','Classics','Quetzal Editores',422);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (68,'David Almond','Fantasy','Porto Editora',309);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (69,'J M Barrie','Fantasy','Faber and Faber',264);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (70,'Nina Bawden','War','Usborne Publishing',238);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (71,'Malorie Blackman','Thriller','Harper Collins',243);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (72,'Frank Boyce','Adventure','Penguin Books',307);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (73,'Chris Bradford','Adventure','Usborne Publishing',264);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (74,'Frances H Burnett','Classics','Harper Collins',384);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (75,'Frances H Burnett','Classics','Editorial Presença',277);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (76,'Lewis Carroll','Classics','Penguin Books',360);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (77,'Lewis Carroll','Classics','Editorial Presença',367);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (78,'Cathy Cassidy','Friends','Porto Editora',403);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (79,'Cathy Cassidy','Fiction','Sextante Editora',373);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (80,'Eoin Colfer','Fantasy','Usborne Publishing',361);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (81,'Susan Coolidge','Classics','Editorial Presença',289);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (82,'Sharon Creech','Poetry','Porto Editora',222);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (83,'Gillian Cross','School','Faber and Faber',382);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (84,'Gillian Cross','Dystopian','Usborne Publishing',428);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (85,'Roald Dahl','Factory','Harper Collins',250);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (86,'Berlie Doherty','Historical','Penguin Books',381);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (87,'Berlie Doherty','Historical','Porto Editora',375);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (88,'Siobhan Dowd','Mystery','Antígona',411);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (89,'Anne Fine','Humour','Harper Collins',235);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (90,'Michael Foreman','Historical','Penguin Books',395);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (91,'Cornelia Funke','Fantasy','Cavalo de Ferro',361);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (92,'Sally Gardner','Mystery','Porto Editora',252);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (93,'Kenneth Grahame','Classics','Usborne Publishing',342);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (94,'Carl Hiaasen','Environmental','Editorial Presença',402);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (95,'Anne Holm','Classics','Harper Collins',225);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (96,'Anthony Horrowitz','Adventure','Penguin Books',252);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (97,'Eva Ibbotson','Adventure','Harper Collins',415);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (98,'Judith Kerr','War','Sextante Editora',303);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (99,'Andrew Lane','Mystery','Usborne Publishing',270);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (100,'Elizabeth Laird','Fiction','Editorial Presença',352);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (101,'Caroline Lawrence','Mystery','Porto Editora',431);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (102,'CS Lewis','Fantasy','Quetzal Editores',403);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (103,'Mary Norton','Classics','Porto Editora',234);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (104,'Andrew Norriss','Funny','Faber and Faber',347);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (105,'RJ Palacio','School','Usborne Publishing',381);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (106,'Arthur Ransome','Adventure','Harper Collins',419);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (107,'Rick Riordan','Fantasy','Penguin Books',428);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (108,'Malcolm Rose','Thriller','Usborne Publishing',245);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (109,'JK Rowling','Fantasy','Harper Collins',361);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (110,'Louis Sachar','Adventure','Editorial Presença',318);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (111,'Kate Saunders','War','Penguin Books',230);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (112,'Alex Scarrow','Adventure','Editorial Presença',251);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (113,'Marcus Sedgwick','Adventure','Porto Editora',367);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (114,'Anna Sewell','Classics','Sextante Editora',391);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (115,'Dodie Smith','Classics','Usborne Publishing',230);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (116,'Lemony Snicket','Adventure','Editorial Presença',331);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (117,'Noel Streatfield','Family','Porto Editora',398);
INSERT INTO FNAC.Livro (id_artigo,autor,genero,editora,n_paginas) VALUES (118,'Robert Westall','Historical','Faber and Faber',312);