-- INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato)
Use FNAC;
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1004,'Indie Rock','David Bowie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1005,'Indie Rock','Kings of Leon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1006,'Techno','Paloma Faith','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1007,'Indie Rock','Eric Clapton & Cream','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1008,'Rock','Fleetwood Mac','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1009,'Pop','Red Hot Chili Peppers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1010,'Rock','Stereophonics','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1011,'Indie Rock','Paul Young','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1012,'Jazz','Whitney Houston','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1013,'Rock','Blur','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1014,'Jazz','Bruce Springsteen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1015,'Pop','George Michael','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1016,'Metal','Dua Lipa','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1017,'Pop','Eagles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1018,'EDM','Duran Duran','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1019,'Metal','Bryan Adams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1020,'Rock','David Guetta','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1021,'Rock','Twenty One Pilots','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1022,'Techno','The Seekers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1023,'Pop','Johnny Cash','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1024,'Jazz','Andy Williams','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1025,'Rock','Wham!','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1026,'Metal','London Grammar','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1027,'Rock','Ariana Grande','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1028,'Rock','Blondie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1029,'Pop','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1030,'Blues','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1031,'Blues','Madness','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1032,'EDM','Green Day','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1033,'Rock','P!nk','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1034,'Indie Rock','Electric Light Orchestra','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1035,'Blues','M People','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1036,'Blues','Texas','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1037,'Metal','Christina Aguilera','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1038,'Pop','Portishead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1039,'Pop','Coldplay','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1040,'Pop','Rihanna','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1041,'Indie Rock','Drake','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1042,'Blues','UB40','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1043,'Hip Hop','Neil Diamond','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1044,'Metal','Duran Duran','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1045,'Jazz','Enya','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1046,'Metal','Elvis Presley','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1047,'Rock','George Michael','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1048,'Hip Hop','Calvin Harris','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1049,'Rock','Def Leppard','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1050,'Metal','Paul Weller','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1051,'Jazz','Moby','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1052,'Pop','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1053,'Rock','Perry Como','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1054,'Rock','Erasure','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1055,'Pop','Enigma','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1056,'Blues','Dr. Dre','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1057,'Blues','Vangelis','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1058,'Pop','Madness','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1059,'Metal','Simon & Garfunkel','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1060,'Rock','The Beatles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1061,'Techno','Justin Timberlake','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1062,'Rock','Kasabian','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1063,'Rock','Ariana Grande','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1064,'Rock','Maroon 5','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1065,'Rock','Elton John','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1066,'Rock','George Michael','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1067,'Metal','Phil Collins','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1068,'Blues','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1069,'Jazz','Rag’n’Bone Man','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1070,'EDM','Pink Floyd','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1071,'Blues','INXS','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1072,'Indie Rock','Manic Street Preachers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1073,'Techno','Britney Spears','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1074,'Pop','Leona Lewis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1075,'Blues','Jessie J','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1076,'Techno','Jake Bugg','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1077,'Metal','Sia','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1078,'Techno','Whitney Houston','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1079,'Indie Rock','UB40','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1080,'Rock','Michael Jackson','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1081,'Jazz','Duffy','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1082,'Metal','Chase & Status','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1083,'Rock','Drake','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1084,'Rock','Eric Clapton','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1085,'EDM','Natalie Imbruglia','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1086,'EDM','Kaiser Chiefs','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1087,'Blues','Biffy Clyro','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1088,'Pop','Panic! at the Disco','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1089,'Pop','John Lennon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1090,'Jazz','Elton John','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1091,'Pop','Electric Light Orchestra','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1092,'Pop','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1093,'Metal','Fatboy Slim','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1094,'Pop','Katie Melua','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1095,'Pop','The Kooks','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1096,'Blues','Gregory Porter','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1097,'Blues','J Hus','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1098,'Hip Hop','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1099,'Techno','The Prodigy','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1100,'Rock','U2','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1101,'Techno','Ben Howard','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1102,'Pop','Bee Gees','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1103,'Blues','Robbie Williams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1104,'EDM','Dido','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1105,'Hip Hop','The Script','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1106,'Pop','David Bowie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1107,'Indie Rock','Amy Winehouse','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1108,'Blues','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1109,'Jazz','Elbow','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1110,'Pop','Original Cast','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1111,'Hip Hop','Ellie Goulding','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1112,'Rock','George Mitchell Minstrels','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1113,'Metal','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1114,'Hip Hop','Bon Jovi','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1115,'Pop','Paolo Nutini','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1116,'Blues','Linkin Park','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1117,'Jazz','Eurythmics','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1118,'Rock','Celine Dion','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1119,'Pop','The Corrs','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1120,'Pop','Lana Del Rey','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1121,'Hip Hop','ZZ Top','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1122,'Jazz','Catfish and the Bottlemen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1123,'Pop','Katy Perry','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1124,'Pop','The Stone Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1125,'Techno','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1126,'Rock','The Carpenters','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1127,'Techno','Simply Red','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1128,'Techno','The Beautiful South','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1129,'Hip Hop','Emeli Sandé','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1130,'Jazz','Bruce Springsteen','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1131,'Rock','The Killers','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1132,'Metal','Adele','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1133,'Techno','Eminem','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1134,'Metal','Travis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1135,'Pop','Robbie Williams','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1136,'Techno','Robbie Williams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1137,'Hip Hop','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1138,'Hip Hop','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1139,'Rock','Take That','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1140,'Jazz','Ed Sheeran','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1141,'Rock','Garbage','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1142,'Rock','Scissor Sisters','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1143,'Pop','Paul McCartney and Wings','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1144,'EDM','ABBA','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1145,'Jazz','Barbra Streisand','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1146,'Rock','Kate Bush','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1147,'Rock','Massive Attack','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1148,'Jazz','Keane','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1149,'Pop','James Blunt','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1150,'Hip Hop','Led Zeppelin','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1151,'Indie Rock','Carole King','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1152,'Jazz','Lionel Richie','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1153,'Pop','Celine Dion','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1154,'Blues','M People','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1155,'Pop','Beyoncé','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1156,'Pop','Rod Stewart','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1157,'Rock','Barry White','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1158,'Blues','Massive Attack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1159,'Rock','One Direction','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1160,'Pop','Bastille','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1161,'Pop','U2','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1162,'Hip Hop','Plan B','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1163,'Hip Hop','Justin Bieber','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1164,'Pop','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1165,'Hip Hop','Green Day','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1166,'Metal','The Killers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1167,'Hip Hop','Imagine Dragons','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1168,'Hip Hop','Post Malone','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1169,'Blues','Florence and the Machine','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1170,'Techno','Coldplay','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1171,'Hip Hop','Rod Stewart','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1172,'Rock','Bon Jovi','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1173,'Blues','Michael Jackson','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1174,'Rock','Tina Turner','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1175,'Blues','Michael Bublé','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1176,'Metal','Eagles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1177,'Rock','Paolo Nutini','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1178,'EDM','Rihanna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1179,'Metal','Phil Collins','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1180,'Rock','Phil Collins','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1181,'Pop','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1182,'Indie Rock','Lighthouse Family','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1183,'Rock','David Gray','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1184,'Rock','Lady Gaga','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1185,'Hip Hop','Van Morrison','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1186,'Indie Rock','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1187,'Rock','Red Hot Chili Peppers','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1188,'Indie Rock','UB40','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1189,'Metal','Kings of Leon','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1190,'Hip Hop','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1191,'Rock','The Corrs','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1192,'Pop','Red Hot Chili Peppers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1193,'Rock','The Beatles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1194,'Blues','David Bowie','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1195,'Rock','Simply Red','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1196,'Techno','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1197,'Blues','The Verve','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1198,'Blues','Shania Twain','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1199,'Pop','Paul Simon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1200,'Rock','George Ezra','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1201,'Rock','Taylor Swift','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1202,'Indie Rock','The 1975','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1203,'Rock','Original Broadway Cast','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1204,'Jazz','Eva Cassidy','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1205,'Rock','Buddy Holly','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1206,'Rock','Bon Jovi','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1207,'Hip Hop','Bruno Mars','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1208,'EDM','P!nk','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1209,'Pop','Lionel Richie','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1210,'EDM','Madonna','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1211,'Rock','Norah Jones','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1212,'Indie Rock','Little Mix','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1213,'EDM','The Beach Boys','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1214,'Pop','Barry Manilow','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1215,'EDM','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1216,'Metal','Adele','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1217,'Hip Hop','Tina Turner','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1218,'Blues','Coldplay','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1219,'Metal','Michael Bublé','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1220,'Metal','Queen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1221,'EDM','ABBA','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1222,'Rock','Bob Marley and the Wailers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1223,'Techno','Fleetwood Mac','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1224,'EDM','Pink Floyd','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1225,'Rock','Meat Loaf','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1226,'Rock','Michael Jackson','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1227,'EDM','Oasis','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1228,'Indie Rock','Amy Winehouse','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1229,'Techno','Eminem','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1230,'Indie Rock','Original Soundtrack','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1231,'Rock','Fleetwood Mac','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1232,'Rock','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1233,'Techno','Foo Fighters','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1234,'Hip Hop','Oasis','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1235,'Techno','Nirvana','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1236,'Blues','Simon & Garfunkel','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1237,'EDM','Simon & Garfunkel','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1238,'Indie Rock','Oasis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1239,'Blues','Arctic Monkeys','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1240,'Techno','Guns N’ Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1241,'Rock','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1242,'EDM','Whitney Houston','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1243,'Indie Rock','Phil Collins','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1244,'Rock','Tracy Chapman','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1245,'Rock','Ed Sheeran','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1246,'Pop','Mike Oldfield','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1247,'Pop','Michael Jackson','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1248,'Pop','Guns N’ Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1249,'Pop','The Beatles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1250,'Blues','Dire Straits','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1251,'Pop','Adele','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1252,'Rock','Sam Smith','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1253,'Hip Hop','Arctic Monkeys','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1254,'Blues','Queen','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1255,'EDM','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1256,'Hip Hop','The Killers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1257,'Jazz','R.E.M.','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1258,'EDM','Frank Sinatra','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1259,'Jazz','The Beatles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1260,'Techno','Michael Jackson','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1261,'Pop','Alanis Morissette','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1262,'Techno','Take That','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1263,'Metal','Mumford & Sons','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1264,'Pop','R.E.M.','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1265,'Pop','Adele','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1266,'Blues','The Beatles','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1267,'Metal','Jess Glynne','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1268,'Rock','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1269,'Hip Hop','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1270,'Pop','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1271,'Pop','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1272,'Rock','Dire Straits','CD');