-- INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao)
Use FNAC;
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1,'To Kill a Mockingbird','Livro',16.3,1997,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (2,'Pride and Prejudice','Livro',16.8,2000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (3,'Anne Frank: The Diary of a Young Girl','Livro',12.6,1956,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (4,'1984','Livro',14.9,1968,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (5,'Harry Potter and the Sorcerer’s Stone','Livro',14.7,2009,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (6,'The Lord of the Rings','Livro',14,2010,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (7,'The Great Gatsby','Livro',17.6,2007,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (8,'Charlotte’s Web','Livro',15.4,1980,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (9,'Little Women','Livro',9.3,1992,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (10,'The Hobbit','Livro',11.4,1957,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (11,'Fahrenheit 451','Livro',16.2,1979,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (12,'Jane Eyre','Livro',11.1,1978,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (13,'Gone With the Wind','Livro',17,1975,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (14,'Animal Farm','Livro',15.1,1996,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (15,'The Catcher in the Rye','Livro',9.5,1992,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (16,'The Adventures of Huckleberry Finn','Livro',12.5,1952,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (17,'The Help','Livro',12.8,1963,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (18,'The Grapes of Wrath','Livro',10.1,1973,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (19,'The Lion, the Witch and the Wardrobe','Livro',9,1991,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (20,'The Hunger Games','Livro',10.5,1981,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (21,'The Book Thief','Livro',9.4,1975,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (22,'Lord of the Flies','Livro',11.9,1958,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (23,'The Kite Runner','Livro',17.2,2002,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (24,'Night','Livro',14.5,1974,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (25,'Hamlet','Livro',17.2,2004,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (26,'A Tale of Two Cities','Livro',15.4,1961,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (27,'A Wrinkle in Time','Livro',17.2,1996,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (28,'The Hitchhiker’s Guide to the Galaxy','Livro',15.2,1959,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (29,'A Christmas Carol','Livro',10,2001,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (30,'Of Mice and Men','Livro',9.5,1985,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (31,'The Secret Garden','Livro',12.9,1957,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (32,'Romeo and Juliet','Livro',13.1,1996,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (33,'The Handmaid’s Tale','Livro',13.1,2018,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (34,'Brave New World','Livro',12.7,1995,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (35,'The Little Prince','Livro',15.5,1951,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (36,'Where the Sidewalk Ends','Livro',9.6,1961,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (37,'Wuthering Heights','Livro',17.4,1997,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (38,'The Giver','Livro',9.6,1994,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (39,'Anne of Green Gables','Livro',13.2,1966,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (40,'Macbeth','Livro',10.5,2018,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (41,'The Adventures of Tom Sawyer','Livro',14.7,2012,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (42,'Harry Potter and the Deathly Hallows','Livro',9.5,1968,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (43,'Frankenstein','Livro',15,1994,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (44,'The Holy Bible: New King James Version','Livro',11.3,1956,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (45,'The Girl with the Dragon Tattoo','Livro',17.8,2005,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (46,'The Count of Monte Cristo','Livro',14,2008,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (47,'The Fault in Our Stars','Livro',9.8,1964,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (48,'The Color Purple','Livro',11.1,1983,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (49,'East of Eden','Livro',10.5,1978,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (50,'A Tree Grows in Brooklyn','Livro',12.5,1962,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (51,'Catch-22','Livro',14.2,2003,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (52,'In Cold Blood','Livro',15.7,2011,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (53,'The Stand','Livro',17.3,1950,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (54,'Alice in Wonderland','Livro',10.2,1957,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (55,'Watership Down','Livro',9.7,1997,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (56,'Anna Karenina','Livro',9.8,1983,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (57,'Ender’s Game','Livro',13.2,1959,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (58,'Great Expectations','Livro',16.3,1986,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (59,'Rebecca','Livro',14.4,1999,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (60,'Memoirs of a Geisha: A Novel','Livro',15.4,1992,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (61,'The Adventures of Sherlock Holmes','Livro',14.9,2018,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (62,'Harry Potter and the Prisoner of Azkaban','Livro',14.8,2001,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (63,'The Old Man and the Sea','Livro',10,1998,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (64,'Game of Thrones (A Song of Ice and Fire Book)','Livro',15.6,1975,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (65,'The Princess Bride','Livro',16.1,1993,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (66,'Charlie and the Chocolate Factory','Livro',10.7,2007,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (67,'Life of Pi','Livro',14,1950,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (68,'Skellig','Livro',15.1,2017,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (69,'Peter Pan','Livro',11.9,1971,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (70,'Carrie’s War','Livro',12.2,2019,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (71,'Hacker','Livro',13.1,1998,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (72,'Cottrell Millions','Livro',12.5,2016,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (73,'Young Samurai series','Livro',11.8,2014,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (74,'The Secret Garden','Livro',15.4,1972,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (75,'A Little Princess','Livro',15,2003,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (76,'Alice’s Adventures in Wonderland','Livro',15,2008,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (77,'Through the Looking Glass Classics','Livro',9.2,1955,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (78,'Dizzy','Livro',12.6,1979,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (79,'Looking Glass Girl','Livro',15.4,1972,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (80,'Artemis Fowl series','Livro',12.1,1997,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (81,'What Katy Did','Livro',9.3,1990,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (82,'Heartbeat','Livro',17.3,1996,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (83,'The Demon Headmaster','Livro',9.6,1967,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (84,'After Tomorrow','Livro',12.7,1994,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (85,'Charlie and the Chocolate','Livro',15.7,1977,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (86,'Granny was a Buffer Girl','Livro',15.3,1968,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (87,'Street Child','Livro',14.8,1988,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (88,'The London Eye Mystery','Livro',15.7,1983,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (89,'Madame Doubtfire','Livro',16.2,1952,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (90,'War Game','Livro',12.6,1969,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (91,'The Thief Lord','Livro',9.6,2007,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (92,'I Coriander','Livro',11.8,2006,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (93,'The Wind in the Willows','Livro',15.2,1965,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (94,'Hoot','Livro',14.7,1967,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (95,'I am David','Livro',17.5,1977,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (96,'Alex Rider series','Livro',14,1969,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (97,'Journey to the River Sea','Livro',9.3,1967,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (98,'When Hitler Stole Pink Rabbit','Livro',17,1960,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (99,'Young Sherlock Holmes series','Livro',16.4,1950,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (100,'Kiss the Dust','Livro',10.9,1951,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (101,'The Roman Mysteries series','Livro',9.9,1960,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (102,'Chronicles of Narnia series','Livro',13.5,1999,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (103,'The Borrowers','Livro',10,1953,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (104,'Aquilla','Livro',16.7,1968,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (105,'Wonder','Livro',13.6,2016,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (106,'Swallows and Amazons','Livro',13.1,1981,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (107,'Percy Jackson series','Livro',13.4,2012,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (108,'Kiss of Death','Livro',11.9,1993,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (109,'Harry Potter series','Livro',14.3,1979,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (110,'Holes','Livro',10.1,2019,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (111,'Five Children on the Western Front','Livro',14.4,1999,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (112,'Timeriders series','Livro',11.2,2007,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (113,'She is not Invisible','Livro',12,1950,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (114,'Black Beauty','Livro',12,1974,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (115,'The Hundred and One Dalmatians','Livro',11.3,2006,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (116,'A Series of Unfortunate Events','Livro',15.4,1993,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (117,'Ballet Shoes','Livro',14,1952,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (118,'The Machine Gunners','Livro',12.9,1966,5.9);