-- INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao)
Use FNAC;
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1004,'Legacy','Musica',3.8,2016,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1005,'Because of the Times','Musica',15.3,2007,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1006,'Do You Want the Truth or Something Beautiful?','Musica',19.4,2009,3.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1007,'The Cream of Eric Clapton','Musica',6.3,1987,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1008,'Tango in the Night','Musica',15.2,1987,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1009,'Blood Sugar Sex Magik','Musica',28.6,1991,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1010,'Performance and Cocktails','Musica',7,1999,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1011,'No Parlez','Musica',15.6,1983,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1012,'Whitney Houston','Musica',17.1,1985,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1013,'Parklife','Musica',3.9,1994,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1014,'Greatest Hits','Musica',17.7,1995,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1015,'Older','Musica',18.1,1996,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1016,'Dua Lipa','Musica',3.3,2017,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1017,'Their Greatest Hits (1971–1975)','Musica',15.8,1976,3.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1018,'Duran Duran','Musica',24.5,1981,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1019,'Reckless','Musica',7.5,1985,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1020,'Nothing but the Beat','Musica',16.2,2011,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1021,'Blurryface','Musica',24.7,2015,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1022,'Best of the Seekers','Musica',8.8,1968,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1023,'At San Quentin','Musica',13.1,1969,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1024,'Greatest Hits','Musica',23.7,1970,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1025,'Fantastic','Musica',4.6,1983,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1026,'If You Wait','Musica',13.6,2013,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1027,'Dangerous Woman','Musica',17.7,2016,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1028,'Parallel Lines','Musica',3.6,1978,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1029,'Pablo Honey','Musica',13,1993,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1030,'Up to Now','Musica',24.2,2009,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1031,'Divine Madness','Musica',5.9,1992,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1032,'Dookie','Musica',16.2,1994,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1033,'I’m Not Dead','Musica',23.8,2006,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1034,'Out of the Blue','Musica',8.2,1977,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1035,'Elegant Slumming','Musica',18.2,1993,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1036,'White on Blonde','Musica',18.8,1997,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1037,'Stripped','Musica',8.2,2002,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1038,'Dummy','Musica',15.8,1994,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1039,'X&Y','Musica',19.4,2005,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1040,'Loud','Musica',3.9,2010,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1041,'Views','Musica',13.7,2016,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1042,'Labour of Love','Musica',23.8,1983,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1043,'The Jazz Singer (OST)','Musica',8.6,1980,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1044,'Rio','Musica',16.8,1982,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1045,'Shepherd Moons','Musica',27,1991,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1046,'ELV1S: 30 No. 1 Hits','Musica',6,2002,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1047,'Ladies & Gentlemen: The Best of George Michael','Musica',14.1,1998,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1048,'18 Months','Musica',24.1,2012,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1049,'Hysteria','Musica',4.5,1987,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1050,'Stanley Road','Musica',16.9,1995,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1051,'Play','Musica',17.5,1999,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1052,'Dr Zhivago','Musica',8.7,1966,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1053,'And I Love You So','Musica',18.6,1973,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1054,'The Circus','Musica',18.7,1987,5.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1055,'MCMXC a.D.','Musica',3.2,1990,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1056,'2001','Musica',16,1999,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1057,'Chariots of Fire (OST)','Musica',19.3,1981,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1058,'Complete Madness','Musica',3.6,1982,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1059,'Sounds of Silence','Musica',13.8,1966,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1060,'Abbey Road','Musica',26.5,1969,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1061,'Justified','Musica',5.1,2002,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1062,'Kasabian','Musica',13.2,2004,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1063,'My Everything','Musica',18.1,2014,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1064,'Singles','Musica',3,2015,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1065,'The Very Best of Elton John','Musica',16.3,1990,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1066,'Twenty Five','Musica',20.9,2006,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1067,'Hits','Musica',5.4,1998,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1068,'Just Enough Education to Perform','Musica',16.7,2001,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1069,'Human','Musica',18.3,2017,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1070,'Wish You Were Here','Musica',3.5,1975,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1071,'Kick','Musica',17,1987,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1072,'Everything Must Go','Musica',26.8,1996,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1073,'...Baby One More Time','Musica',7.5,1999,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1074,'Spirit','Musica',14.2,2007,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1075,'Who You Are','Musica',19.2,2011,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1076,'Jake Bugg','Musica',8.8,2012,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1077,'1000 Forms of Fear','Musica',17,2014,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1078,'Whitney','Musica',21.9,1987,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1079,'Labour of Love II','Musica',6.8,1989,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1080,'Dangerous','Musica',18.8,1991,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1081,'Rockferry','Musica',23.8,2008,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1082,'No More Idols','Musica',6.8,2011,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1083,'Take Care','Musica',16,2011,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1084,'Unplugged','Musica',23.9,1992,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1085,'Left of the Middle','Musica',3.8,1997,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1086,'Employment','Musica',17.1,2005,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1087,'Only Revolutions','Musica',21.2,2009,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1088,'Death of a Bachelor','Musica',5,2016,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1089,'Imagine','Musica',17.7,1971,4.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1090,'Goodbye Yellow Brick Road','Musica',17.9,1973,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1091,'A New World Record','Musica',6.4,1976,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1092,'OK Computer','Musica',13.1,1997,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1093,'You’ve Come a Long Way, Baby','Musica',17.9,1998,5.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1094,'Call Off the Search','Musica',4,2003,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1095,'Inside In / Inside Out','Musica',17.6,2006,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1096,'Liquid Spirit','Musica',17.4,2013,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1097,'Common Sense','Musica',6.5,2017,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1098,'The Greatest Showman: Original Soundtrack','Musica',18.1,2018,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1099,'Music for the Jilted Generation','Musica',18.2,1994,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1100,'War','Musica',8.8,1983,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1101,'Every Kingdom','Musica',15.2,2011,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1102,'The Very Best of the Bee Gees','Musica',17.5,1990,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1103,'Life thru a Lens','Musica',4.2,1997,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1104,'No Angel','Musica',17.2,2000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1105,'The Script','Musica',23.6,2008,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1106,'Hunky Dory','Musica',4.5,1972,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1107,'Frank','Musica',15.8,2003,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1108,'Final Straw','Musica',26,2004,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1109,'The Seldom Seen Kid','Musica',5.3,2008,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1110,'The Phantom of the Opera','Musica',13.5,1987,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1111,'Halcyon','Musica',21.5,2012,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1112,'The Black and White Minstrel Show','Musica',3.8,1960,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1113,'Decade in the Sun: Best of Stereophonics','Musica',13.2,2008,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1114,'Slippery When Wet','Musica',19.3,1986,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1115,'Sunny Side Up','Musica',8.9,2009,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1116,'Hybrid Theory','Musica',15.4,2001,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1117,'Greatest Hits','Musica',23.7,1991,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1118,'The Colour of My Love','Musica',6.1,1994,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1119,'Forgiven, Not Forgotten','Musica',14.5,1996,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1120,'Born to Die','Musica',20,2012,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1121,'Eliminator','Musica',3.2,1983,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1122,'The Balcony','Musica',15.3,2014,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1123,'Teenage Dream','Musica',27,2010,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1124,'The Stone Roses','Musica',5.7,1989,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1125,'Ray of Light','Musica',13.5,1998,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1126,'The Singles: 1969–1973','Musica',18.4,1974,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1127,'Picture Book','Musica',7,1985,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1128,'Carry On up the Charts','Musica',13.5,1994,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1129,'Our Version of Events','Musica',27.1,2012,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1130,'Born in the U.S.A.','Musica',6.8,1984,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1131,'Direct Hits','Musica',15,2013,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1132,'25','Musica',26.1,2015,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1133,'The Slim Shady LP','Musica',6.8,1999,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1134,'The Man Who','Musica',15.6,1999,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1135,'I’ve Been Expecting You','Musica',24,1998,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1136,'Greatest Hits','Musica',3.9,2004,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1137,'Dire Straits','Musica',14.3,1978,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1138,'The Unforgettable Fire','Musica',25,1984,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1139,'Beautiful World','Musica',7.9,2006,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1140,'÷','Musica',16.1,2017,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1141,'Garbage','Musica',17.4,1995,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1142,'Scissor Sisters','Musica',7.5,2004,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1143,'Band on the Run','Musica',14.2,1973,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1144,'Greatest Hits','Musica',26.8,1976,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1145,'Love Songs','Musica',4,1982,4.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1146,'The Whole Story','Musica',13.6,1986,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1147,'Blue Lines','Musica',20.4,1991,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1148,'Hopes and Fears','Musica',4.4,2004,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1149,'Back to Bedlam','Musica',17.8,2005,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1150,'Led Zeppelin II','Musica',24.1,1969,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1151,'Tapestry','Musica',5.8,1971,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1152,'Back to Front','Musica',15.1,1992,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1153,'Falling into You','Musica',26.4,1996,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1154,'Bizarre Fruit/Bizarre Fruit II','Musica',5.4,1994,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1155,'I Am... Sasha Fierce','Musica',14.6,2008,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1156,'Some Guys Have All the Luck','Musica',21.3,2008,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1157,'The Collection','Musica',7.3,1988,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1158,'Protection/No Protection','Musica',17.3,1994,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1159,'Up All Night','Musica',21,2011,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1160,'Bad Blood','Musica',8.7,2013,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1161,'The Best of 1980–1990','Musica',18,1998,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1162,'The Defamation of Strickland Banks','Musica',27.9,2010,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1163,'Purpose','Musica',4.6,2015,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1164,'Madonna','Musica',17.4,1984,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1165,'American Idiot','Musica',24.9,2004,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1166,'Sam’s Town','Musica',4,2006,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1167,'Night Visions','Musica',15,2013,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1168,'Stoney','Musica',25.5,2016,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1169,'Lungs','Musica',8,2009,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1170,'Parachutes','Musica',16.1,2000,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1171,'The Best of Rod Stewart','Musica',25.4,1976,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1172,'Greatest Hits','Musica',16.8,2010,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1173,'Bad','Musica',17.8,1987,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1174,'Simply the Best','Musica',6.6,1991,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1175,'Crazy Love','Musica',18.1,2009,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1176,'The Very Best of the Eagles','Musica',22.2,1994,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1177,'These Streets','Musica',7.7,2006,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1178,'Good Girl Gone Bad','Musica',18.9,2007,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1179,'No Jacket Required','Musica',22.5,1985,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1180,'Hello, I Must Be Going!','Musica',3.9,1982,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1181,'West Side Story','Musica',13.1,1962,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1182,'Ocean Drive','Musica',24.9,1995,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1183,'White Ladder','Musica',4.5,2000,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1184,'The Fame','Musica',18.1,2009,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1185,'The Best of Van Morrison','Musica',26.5,1990,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1186,'Oklahoma!','Musica',8.7,1956,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1187,'Californication','Musica',18.8,1999,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1188,'The Best of UB40 – Volume One','Musica',19.1,1987,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1189,'Only by the Night','Musica',4.9,2008,5.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1190,'Alchemy – Dire Straits Live','Musica',13.1,1984,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1191,'Talk on Corners','Musica',26.8,1997,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1192,'Greatest Hits','Musica',5.5,2003,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1193,'1967-1970','Musica',18.3,1973,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1194,'Best of Bowie','Musica',26.1,2002,5.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1195,'Stars','Musica',7.4,1991,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1196,'Word Gets Around','Musica',16.7,1997,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1197,'Urban Hymns','Musica',26.6,1997,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1198,'Come On Over','Musica',5.9,1998,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1199,'Graceland','Musica',16.1,1986,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1200,'Wanted on Voyage','Musica',27.9,2014,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1201,'1989','Musica',7.1,2014,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1202,'The 1975','Musica',15.9,2013,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1203,'My Fair Lady','Musica',25.5,1958,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1204,'Songbird','Musica',6.6,1998,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1205,'The Buddy Holly Story','Musica',15.3,1959,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1206,'Cross Road – The Best of Bon Jovi','Musica',19.8,1994,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1207,'Doo-Wops & Hooligans','Musica',6.5,2010,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1208,'Greatest Hits... So Far!!!','Musica',18.6,2010,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1209,'Can’t Slow Down','Musica',24.2,1983,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1210,'Like a Virgin','Musica',7.7,1984,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1211,'Come Away with Me','Musica',17.3,2002,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1212,'Glory Days','Musica',17,2016,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1213,'Best of The Beach Boys','Musica',3.1,1966,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1214,'Manilow Magic','Musica',13.5,1979,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1215,'Eyes Open','Musica',20.4,2006,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1216,'25','Musica',8.6,2015,5.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1217,'Private Dancer','Musica',15.8,1984,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1218,'A Rush of Blood to the Head','Musica',20,2002,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1219,'Call Me Irresponsible','Musica',3.2,2007,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1220,'Greatest Hits','Musica',15.6,1981,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1221,'Gold: Greatest Hits','Musica',22,1992,3.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1222,'Legend','Musica',7.2,1984,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1223,'Rumours','Musica',18.8,1977,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1224,'The Dark Side of the Moon','Musica',26,1973,5.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1225,'Bat Out of Hell','Musica',3.5,1978,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1226,'Number Ones','Musica',17.1,2003,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1227,'(What’s the Story) Morning Glory?','Musica',18.2,1995,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1228,'Back to Black','Musica',8.9,2006,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1229,'Curtain Call: The Hits','Musica',16.7,2005,4.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1230,'The Sound of Music','Musica',17.9,1965,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1231,'The Very Best of Fleetwood Mac','Musica',4.9,2002,4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1232,'The Immaculate Collection','Musica',14.2,1990,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1233,'Greatest Hits','Musica',17.5,2009,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1234,'Definitely Maybe','Musica',5,1994,3.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1235,'Nevermind','Musica',14.6,1991,5.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1236,'Simon and Garfunkel’s Greatest Hits','Musica',18.7,1972,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1237,'Bridge over Troubled Water','Musica',8.6,1970,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1238,'Time Flies... 1994–2009','Musica',18,2010,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1239,'AM','Musica',20.9,2013,3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1240,'Greatest Hits','Musica',6.8,2004,4.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1241,'South Pacific','Musica',14.3,1958,3.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1242,'The Ultimate Collection','Musica',5.3,2008,3.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1243,'Face Value','Musica',18.9,1981,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1244,'Tracy Chapman','Musica',21.3,1988,4.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1245,'x','Musica',6.6,2014,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1246,'Tubular Bells','Musica',13.1,1973,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1247,'Thriller','Musica',27.1,1982,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1248,'Appetite for Destruction','Musica',5,1987,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1249,'Sgt. Pepper’s Lonely Hearts Club Band','Musica',15.7,1967,4.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1250,'Brothers in Arms','Musica',19.3,1985,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1251,'21','Musica',7.1,2011,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1252,'In the Lonely Hour','Musica',17.9,2014,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1253,'Whatever People Say I Am, That’s What I’m Not','Musica',20,2006,5.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1254,'Greatest Hits II','Musica',3.6,1991,4.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1255,'Making Movies','Musica',14.8,1980,3.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1256,'Hot Fuss','Musica',20.9,2004,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1257,'Automatic for the People','Musica',8.2,1992,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1258,'My Way: The Best of Frank Sinatra','Musica',14.7,1997,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1259,'1','Musica',27.7,2000,5.5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1260,'Off the Wall','Musica',3.5,1979,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1261,'Jagged Little Pill','Musica',17.6,1995,3.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1262,'Never Forget – The Ultimate Collection','Musica',28,2005,3.7);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1263,'Sigh No More','Musica',6.9,2009,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1264,'Out of Time','Musica',14.6,1991,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1265,'19','Musica',18,2008,4.8);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1266,'1962–1966','Musica',3,1973,3.4);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1267,'I Cry When I Laugh','Musica',14.9,2015,3.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1268,'Under a Blood Red Sky','Musica',28.7,1983,5.2);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1269,'The King and I','Musica',3.7,1956,4.1);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1270,'The Bends','Musica',16.3,1995,5);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1271,'The Joshua Tree','Musica',26.9,1987,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1272,'Love over Gold','Musica',14.6,1982,5.8);